version: "3.8"

services:
  web:
    build: .
    container_name: php-web
    ports:
      - "3306:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gundam_shop
    volumes:
      - db_data:/var/lib/mysql
      - ./gundam_shop.sql:/docker-entrypoint-initdb.d/gundam_shop.sql:ro

volumes:
  db_data:
